services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pythonbackend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

      # Configuração de banco de dados (SQLite ou Postgres)
      - DB_TYPE=${DB_TYPE}
      - DB_PATH=${DB_PATH}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

    volumes:
      - "/home/plena/present/agent:/app"
