services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pythonbackend
    ports:
      - "8000:8000"
    environment:
      
      - OPENAI_API_KEY=${OPENAI_API_KEY}